apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cupicoin
  annotations:
    github.com/project-slug: julianescobarje/cupicoin
spec:
  type: other
  lifecycle: unknown
  owner: backstage
